CREATE TABLE `submitted_properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`sourceUrl` text NOT NULL,
	`sourcePlatform` varchar(64),
	`status` enum('pending','analyzing','ready','error') NOT NULL DEFAULT 'pending',
	`title` varchar(512),
	`address` varchar(255),
	`city` varchar(128),
	`district` varchar(128),
	`zipCode` varchar(20),
	`propertyType` varchar(64),
	`askingPrice` int,
	`pricePerSqm` int,
	`priceHistory` json,
	`bedrooms` int,
	`bathrooms` int,
	`area` int,
	`floor` varchar(32),
	`yearBuilt` int,
	`energyCertificate` varchar(8),
	`condition_status` varchar(64),
	`daysOnMarket` int,
	`priceReductions` int DEFAULT 0,
	`originalPrice` int,
	`lat` decimal(10,6),
	`lng` decimal(10,6),
	`mainImage` text,
	`images` json,
	`aiScore` int,
	`aiDescription` text,
	`aiPros` json,
	`aiCons` json,
	`aiNeighborhood` text,
	`aiInvestmentAnalysis` text,
	`bargainingPower` int,
	`suggestedOffer` int,
	`originalDescription` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `submitted_properties_id` PRIMARY KEY(`id`)
);
